-- 1. Create the environment
CREATE DATABASE IF NOT EXISTS NEWS_DB;
CREATE SCHEMA IF NOT EXISTS NEWS_DB.RAW;

-- 2. Create the Warehouse
CREATE WAREHOUSE IF NOT EXISTS NEWS_WH 
    WITH WAREHOUSE_SIZE = 'XSMALL' 
    AUTO_SUSPEND = 60    
    AUTO_RESUME = TRUE;

-- 3. Create the table with a UNIQUE constraint
CREATE OR REPLACE TRANSIENT TABLE NEWS_DB.RAW.ARTICLES (
    UUID STRING NOT NULL,
    URL STRING NOT NULL,
    DATE_SCRAPED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    HEADLINE STRING,
    BODY STRING,
    CONSTRAINT pk_uuid PRIMARY KEY (UUID),
    CONSTRAINT unique_url UNIQUE (URL) -- This is the key change!
) COMMENT = 'Landing table for raw news scraper data';